### ISSUE TITLE
Missed type repository link

### ISSUE THREAD

**Issue by meisyal** [ardhinata/ardhinata_crypto#1]
Hi, Ardhinata.

You missed type your repository link. Please, check [your commit] (https://github.com/ardhinata/ardhinata_crypto/commit/0240028827ddae862bf0001d11f9cb58dd1896d9#diff-04c6e90faac2675aa89e2176d2eec7d8R1). It should say https://github.com/ardhinata/ardhinata_crypto. You might be confused between `crypto` and `crypyo` :laughing:.

**Comment by ardhinata** [comment]
Hello,
Thanks @meisyal for clarification. I've patched them in commit 80f312397b0fda1358ca23e23ea59134c36a220e.
This small mistake usually goes unnoticed.

Regards,
@ardhinata

**Comment by meisyal** [comment]
You're welcome, @ardhinata 

Keep up the good work! :+1:
